"""create environments events idempotency tables

Revision ID: 5248ba14595e
Revises: 
Create Date: 2026-09-12 11:56:13.828428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5248ba14595e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('runtime', sa.String(length=255), nullable=False),
    sa.Column('cpu', sa.String(length=64), nullable=False),
    sa.Column('memory', sa.String(length=64), nullable=False),
    sa.Column('slo_availability', sa.Float(), nullable=False),
    sa.Column('ttl_hours', sa.Integer(), nullable=False),
    sa.Column('desired_state', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('environment_id', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=False),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environment_events_correlation_id'), 'environment_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_environment_events_environment_id'), 'environment_events', ['environment_id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_fingerprint', sa.Text(), nullable=False),
    sa.Column('environment_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.PrimaryKeyConstraint('idempotency_key'),
    sa.UniqueConstraint('environment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_environment_events_environment_id'), table_name='environment_events')
    op.drop_index(op.f('ix_environment_events_correlation_id'), table_name='environment_events')
    op.drop_table('environment_events')
    op.drop_table('environments')
    # ### end Alembic commands ###
